Caratulas/App/Cardinal.EasyApps.Caratulas/EasyApps.ED.Caratulas.WebRazor/Controllers/HistoricoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Telerik.Web.Mvc;
using Telerik.Web.Mvc.UI;

using Cardinal.EasyApps.ED.Common.Dal;
using Cardinal.EasyApps.ED.Model;


namespace Cardinal.Caratulas.Controllers
{
    [Authorize]
    public class HistoricoController : Controller
    {
       
        //HistoricoWCF.HitoricoServiceClient servicioWCF = new HistoricoWCF.HitoricoServiceClient();
        //LogerWCF.LogServiceClient logerWCF = new LogerWCF.LogServiceClient();

        IRepository _repository;
        public HistoricoController(IRepository repository)
        {
            _repository = repository;
        	
        }

        public ActionResult VerHistorico(long[] checkedRecords)
        {
            IQueryable<CaratulaCS> caratulas = _repository.GetCaratulas(Session["UserName"].ToString());

            checkedRecords = checkedRecords ?? new long[] { }; 
            ViewData["checkedRecords"] = checkedRecords;

            if (checkedRecords.Any())
            {
                ViewData["checkedOrders"] = caratulas.Where(o => checkedRecords.Contains(o.codigo));
            }

            return View(caratulas);
        }

        [GridAction]
        public ActionResult VerReporte()
        {
            return View();
        }

        [GridAction]
        public ActionResult AnularCaratula(int id)
        {
            bool anulada = _repository.AnularCaratulaCliente(id);

            _repository.LogOperationCaratulas(new LogCaratula { CD_MOVIMIENTO = 2, CD_USUARIO_MOVIMIENTO = Session["UserName"].ToString(), FC_MOVIMIENTO = DateTime.Now, TX_OBSERVACION = "Se anuló un documento" });

            return RedirectToAction("VerHistorico");
        }
    }
}

Caratulas/App/Cardinal.EasyApps.Caratulas/EasyApps.ED.Caratulas.WebRazor/Views/Historico/VerHistorico.cshtml
@model    IEnumerable< Cardinal.EasyApps.ED.Model.CaratulaCS>

@{
    ViewBag.Title = "Ver Historico";
    long[] checkedRecords = (long[])ViewData["checkedRecords"];   
}



<h2>Ver Historico</h2>

@(Html.Telerik().Grid(Model)
       .Name("Grid")
            .Localizable("es-ES")
       .DataKeys(keys => { keys.Add(o => o.codigo); })
       .Columns(columns =>
       {
           columns.Template(
               @<text>
                    <input name="checkedRecords" type="checkbox" value="@item.codigo " title="checkedRecords"
                                             @if (checkedRecords.Contains(item.codigo))
                                             { 
                                                <text>checked="checked"</text>                  
                                             }
                     />
               </text>)
               .Title("").Width(36).HtmlAttributes(new { style = "text-align:center" });
           columns.Bound(o => o.codigo).Title("Numero").Width(70);
           columns.Bound(o => o.fecha).Title("Fecha").Format("{0:dd/MM/yyyy hh:mm}").Width(100);
           columns.Bound(o => o.nombre_empresa).Title("Empresa").Width(150);
           columns.Bound(o => o.plantilla).Title("Plantilla");
           columns.Bound(o => o.FechaInbound).Title("Inbound").Format("{0:dd/MM/yyyy hh:mm}").Width(100);
           columns.Bound(o => o.FechaOutbound).Title("OutBound").Format("{0:dd/MM/yyyy hh:mm}").Width(100);
           columns.Bound(o => o.codigo).Width(60).Format(Html.ActionLink("Ver", "VerReporte", new { id = "{0}" }, new { @class = "botonGrid_2" }).ToHtmlString()).Encoded(false).Title("Ver Reporte");
           columns.Bound(o => o.codigo).Width(60).Format(Html.ActionLink("Anular", "AnularCaratula", new { id = "{0}" }, new { @class = "botonGrid_2" }).ToHtmlString()).Encoded(false).Title("Anular");
       })
       .DetailView(detailView => detailView.Template( 
           @<text>
                @(Html.Telerik().Grid(item.DetalleCampos)
                        .Name("Campos_" + item.codigo)
                        .Columns(columns =>
                        {
                            columns.Bound(o => o.campo).Title("Campo");
                            columns.Bound(o => o.valor).Title("Valor");
                        })
                        .Footer(false)
               )
           </text>
       ))
                            .Scrollable(scrolling => scrolling.Enabled(true).Height(400))
                            .Sortable(sorting => sorting.Enabled(true))
                            .Pageable(paging => paging.PageSize(50))
                            .Filterable(filtering => filtering.Enabled(true))
                            .Groupable(grouping => grouping.Enabled(true))
                                .HtmlAttributes(new { style = "font-size: x-small;" }) 
       
)
<p> 
    <button class="t-button t-state-default" onclick="displayCheckedOrders()">Ver Caratulas seleccionadas</button>
    <script type="text/javascript">
        function displayCheckedOrders() {
            var $checkedRecords = $(':checked');
            if ($checkedRecords.length < 1) {
                alert('Por favor seleccione al menos una caratula.'); return;
            }

            var values =  $(':checked').map(function () {
                return this.value;
            }).get();
           
            var params = "idPrueba=1";
            for (i=0;i< values.length ;i++)
            {
                params += '&checkedRecords=' + values[i];
            }

            var dir = '@Url.Action("VerCaratulas", "Caratula")' + '?' + params;
            window.location = dir;
          }
            </script>

</p>

Caratulas/App/Cardinal.EasyApps.Caratulas/EasyApps.ED.Caratulas.WebRazor/Views/Historico/VerReporte.cshtml
@{
    ViewBag.Title = "Ver Reporte";
}

<h2>Ver Reporte</h2>
@{
    
string dir = Url.Action("GetPdfCaratula", "Caratula", new { caratulaId = ViewContext.RouteData.Values["id"].ToString() });
}

@Html.ActionLink("Volver", "VerHistorico", "Historico") &nbsp; - @Html.ActionLink("Bajar Caratula", "GetPdfCaratula", "Caratula", new { caratulaId = ViewContext.RouteData.Values["id"].ToString() },null)
<br />
<br />
<object data="@dir" width="100%" height="800px" type="application/pdf" />