Core/Cardinal.EasyApps.ED.WebServicies/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cardinal.EasyApps.ED.WebServicies.Controllers
{
    public class AuthController : Controller
    {
        private readonly Cardinal.EasyApps.ED.Common.Dal.IRepository _repository;

        public AuthController(Cardinal.EasyApps.ED.Common.Dal.IRepository repository)
        {
            _repository = repository;
        }
        [HttpPost]
        public ActionResult GetLoginToken(string username, string password)
        {
            string token = LCP.ODO.BusinessObjects.Usuario.GetLoginToken(username,password,"ED");
            Cardinal.EasyApps.ED.Model.LoginAuth loginAuth = new Cardinal.EasyApps.ED.Model.LoginAuth();
            if (!String.IsNullOrEmpty(token))
            {
                loginAuth.Result = "OK";
                loginAuth.Token = token;
            }
            else
            {
                loginAuth.Result = "FAIL";
                loginAuth.Token = string.Empty;
            }
            return new JsonResult
            {
                Data = loginAuth
            };
        }

        [HttpPost]
        public ActionResult IsLoginTokenValid(string loginToken)
        {
            if (!_repository.IsLoginTokenValid(loginToken))
            {
                return new JsonResult
                {
                    Data = "TOKEN INVALID"
                };
            }
            else {
                return new JsonResult
                {
                    Data = "TOKEN VALID"
                };
            }
        }

    }
}

Core/Cardinal.EasyApps.ED.WebServicies/Controllers/ConfiguracionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcMiniProfiler;

namespace Cardinal.EasyApps.ED.WebServicies.Controllers
{
    public class ConfiguracionController : Controller
    {
        private readonly Cardinal.EasyApps.ED.Common.Dal.IRepository _repository;

        public ConfiguracionController(Cardinal.EasyApps.ED.Common.Dal.IRepository repository)
        {
            _repository = repository;
        }

        [HttpPost]
        public ActionResult GetEmpresas(string logintoken)
        {
            //Valido el login Token
            if (!_repository.IsLoginTokenValid(logintoken))
            {
                return new JsonResult
                {
                    Data = "TOKEN INVALID"
                };
            }

            return new JsonResult
            {
                Data = _repository.GetEmpresas(logintoken)
            };
        }

        [HttpPost]
        public ActionResult GetPlantillas(string logintoken)
        { //Valido el login Token
            if (!_repository.IsLoginTokenValid(logintoken))
            {
                return new JsonResult
                {
                    Data = "TOKEN INVALID"
                };
            }

            return new JsonResult
            {
                Data = _repository.GetPlantillasWithLoginToken(logintoken)
            };
        }

        [HttpPost]
        public ActionResult GetPlantillasPorEmpresa(string logintoken, string codigoEmpresa)
        {
            //Valido el login Token
            if (!_repository.IsLoginTokenValid(logintoken))
            {
                return new JsonResult
                {
                    Data = "TOKEN INVALID"
                };
            }
            return new JsonResult
            {
                Data = _repository.GetPlantillas(logintoken,codigoEmpresa)
            };
        }

        [HttpPost]
        public ActionResult GetCamposPorPlantilla(string logintoken, string codigoPlantilla)
        {
            //Valido el login Token
            if (!_repository.IsLoginTokenValid(logintoken))
            {
                return new JsonResult
                {
                    Data = "TOKEN INVALID"
                };
            }
            return new JsonResult
            {
                Data = _repository.GetPlantillaCampos(codigoPlantilla)
            };
        }

        [HttpPost]
        public ActionResult GetTablasExternas(string logintoken)
        {
            var profiler = MiniProfiler.Current; // it's ok if this is null
            using (profiler.Step("Get Tablas Externas"))
            {
                //Valido el login Token
                if (!_repository.IsLoginTokenValid(logintoken))
                {
                    return new JsonResult
                    {
                        Data = "TOKEN INVALID"
                    };
                }
                return new JsonResult
                {

                    Data = _repository.GetTablasExternas()
                };
            }
        }

        //[HttpPost]
        //public ActionResult AddValorTablasExternas(string logintoken,string key string value)
        //{
        //    var profiler = MiniProfiler.Current; // it's ok if this is null
        //    using (profiler.Step("Add Valor Tablas Externas"))
        //    {
        //        //Valido el login Token
        //        if (!_repository.IsLoginTokenValid(logintoken))
        //        {
        //            return new JsonResult
        //            {
        //                Data = "TOKEN INVALID"
        //            };
        //        }
        //       //Valido si existe el key
        //    }
        //}

        [HttpPost]
        public ActionResult AgregarValorTablasExternas(string logintoken, string tablaExterna, string campoId, string campoExterno, 
            string key, string value)
        {
            //Valido el login Token
            if (!_repository.IsLoginTokenValid(logintoken))
            {
                return new JsonResult
                {
                    Data = "TOKEN INVALID"
                };
            }

            Cardinal.EasyApps.ED.Model.ResultadoOperacion resultado = new Cardinal.EasyApps.ED.Model.ResultadoOperacion();
            if (!_repository.ExisteKeyValorTablaExterna(tablaExterna, campoId, campoExterno, key))
            {
                if (_repository.AgregarValorTablaExterna(tablaExterna, campoId, campoExterno, key, value))
                {
                    resultado.Result = "TRUE";
                }
                else
                {
                    resultado.Result = "FALSE";
                }
            }
            else
            {
                resultado.Result = "FALSE";
            }
            return new JsonResult
            {
                Data = resultado
            };
        }

        [HttpPost]
        public ActionResult EditarValorTablasExternas(string logintoken, string tablaExterna, string campoId, string campoExterno,
            string key, string newValue)
        {
            //Valido el login Token
            if (!_repository.IsLoginTokenValid(logintoken))
            {
                return new JsonResult
                {
                    Data = "TOKEN INVALID"
                };
            }

            Cardinal.EasyApps.ED.Model.ResultadoOperacion resultado = new Cardinal.EasyApps.ED.Model.ResultadoOperacion();
            if (_repository.ExisteKeyValorTablaExterna(tablaExterna, campoId, campoExterno, key))
            {
                if (_repository.EditarValorTablaExterna(tablaExterna, campoId, campoExterno, key,newValue))
                {
                    resultado.Result = "TRUE";
                }
                else
                {
                    resultado.Result = "FALSE";
                }
            }
            else
            {
                resultado.Result = "FALSE";
            }
            return new JsonResult
            {
                Data = resultado
            };
        }


        [HttpPost]
        public ActionResult ExisteKeyValorTablaExterna(string logintoken, string tablaExterna, string campoId, string campoExterno,
            string key)
        {
            //Valido el login Token
            if (!_repository.IsLoginTokenValid(logintoken))
            {
                return new JsonResult
                {
                    Data = "TOKEN INVALID"
                };
            }

            Cardinal.EasyApps.ED.Model.ResultadoOperacion resultado = new Cardinal.EasyApps.ED.Model.ResultadoOperacion();
       
            if (_repository.ExisteKeyValorTablaExterna(tablaExterna, campoId, campoExterno, key))
            {
                resultado.Result = "TRUE";
            }
            else
            {
                resultado.Result = "FALSE";
            }
            return new JsonResult
            {
                Data = resultado
            };
        }
    }
}

Core/Cardinal.EasyApps.ED.WebServicies/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cardinal.EasyApps.ED.WebServicies.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Bienvenido a los Servicios Web de EasyDoc.";

            return View();
        }

        public ActionResult GetLoginToken()
        {
            return View();
        }
        public ActionResult Configuracion()
        {
            return View();
        }

        public ActionResult ValidarLoginToken()
        {
            return View();
        }
        

    }
}

Core/Cardinal.EasyApps.ED.WebServicies/Views/Home/Configuracion.cshtml
@{
    ViewBag.Title = "Configuracion";
}

<h2>Configuracion</h2>

<h2>Get Empresas</h2>
@using (Html.BeginForm("GetEmpresas", "Configuracion", null, FormMethod.Post))
{
<div class="editor-label">
  LoginToken
</div>

<div class="editor-field">
@Html.TextBox("logintoken")
</div>


    
     <button type="submit">
                        Get Empresas</button>
    
    
}



<h2>Get Plantillas</h2>
@using (Html.BeginForm("GetPlantillas", "Configuracion", null, FormMethod.Post))
{
<div class="editor-label">
  LoginToken
</div>

<div class="editor-field">
@Html.TextBox("logintoken")
</div>


    
     <button type="submit">
                        Get Plantillas</button>
    
    
}

<h2>Get Plantillas por Empresa</h2>
@using (Html.BeginForm("GetPlantillasPorEmpresa", "Configuracion", null, FormMethod.Post))
{
<div class="editor-label">
  LoginToken
</div>

<div class="editor-field">
@Html.TextBox("logintoken")
</div>
    
<div class="editor-label">
  Codigo Empresa
</div>

<div class="editor-field">
@Html.TextBox("codigoEmpresa")
</div>


    
     <button type="submit">
                        Get Plantillas por Empresa</button>
    
    
}


<h2>Get Campos por Plantilla</h2>
@using (Html.BeginForm("GetCamposPorPlantilla", "Configuracion", null, FormMethod.Post))
{
<div class="editor-label">
  LoginToken
</div>

<div class="editor-field">
@Html.TextBox("logintoken")
</div>
    
<div class="editor-label">
  Codigo Plantilla
</div>

<div class="editor-field">
@Html.TextBox("codigoPlantilla")
</div>


    
     <button type="submit">
                        Get Campos por Plantilla</button>
        
}

<h2>Get Tablas Externas</h2>
@using (Html.BeginForm("GetTablasExternas", "Configuracion", null, FormMethod.Post))
{
<div class="editor-label">
  LoginToken
</div>

<div class="editor-field">
@Html.TextBox("logintoken")
</div>


    
     <button type="submit">
                       Get Tablas Externas</button>


    
    }

    <h2>Existe Valor Tablas Externas</h2>
@using (Html.BeginForm("ExisteKeyValorTablaExterna", "Configuracion", null, FormMethod.Post))
{
<div class="editor-label">
  LoginToken
</div>

<div class="editor-field">
@Html.TextBox("logintoken")
</div>

<div class="editor-label">
 Tabla Externa
</div>

<div class="editor-field">
@Html.TextBox("tablaExterna")
</div>
    <div class="editor-label">
Campo Id
</div>

<div class="editor-field">
@Html.TextBox("campoId")
</div>
    <div class="editor-label">
  Campo Externo
</div>

<div class="editor-field">
@Html.TextBox("campoExterno")
</div>
    <div class="editor-label">
  Key
</div>

<div class="editor-field">
@Html.TextBox("key")
</div>
    
     <button type="submit">
                      Existe Valor Tablas Externas</button>

}

    <h2>Agregar Valor Tablas Externas</h2>
@using (Html.BeginForm("AgregarValorTablasExternas", "Configuracion", null, FormMethod.Post))
{
<div class="editor-label">
  LoginToken
</div>

<div class="editor-field">
@Html.TextBox("logintoken")
</div>

<div class="editor-label">
 Tabla Externa
</div>

<div class="editor-field">
@Html.TextBox("tablaExterna")
</div>
    <div class="editor-label">
Campo Id
</div>

<div class="editor-field">
@Html.TextBox("campoId")
</div>
    <div class="editor-label">
  Campo Externo
</div>

<div class="editor-field">
@Html.TextBox("campoExterno")
</div>
    <div class="editor-label">
  Key
</div>

<div class="editor-field">
@Html.TextBox("key")
</div>
    <div class="editor-label">
  Value
</div>

<div class="editor-field">
@Html.TextBox("value")
</div>
        
     <button type="submit">
                      Agregar Valor Tablas Externas</button>

}

@using (Html.BeginForm("EditarValorTablasExternas", "Configuracion", null, FormMethod.Post))
{
<div class="editor-label">
  LoginToken
</div>

<div class="editor-field">
@Html.TextBox("logintoken")
</div>

<div class="editor-label">
 Tabla Externa
</div>

<div class="editor-field">
@Html.TextBox("tablaExterna")
</div>
    <div class="editor-label">
Campo Id
</div>

<div class="editor-field">
@Html.TextBox("campoId")
</div>
    <div class="editor-label">
  Campo Externo
</div>

<div class="editor-field">
@Html.TextBox("campoExterno")
</div>
    <div class="editor-label">
  Key
</div>

<div class="editor-field">
@Html.TextBox("key")
</div>
    <div class="editor-label">
 New Value
</div>

<div class="editor-field">
@Html.TextBox("newValue")
</div>
        
     <button type="submit">
                      Editar Valor Tablas Externas</button>

}

Core/Cardinal.EasyApps.ED.WebServicies/Views/Home/GetLoginToken.cshtml
@{
    ViewBag.Title = "GetLoginToken";
}


<h2>Get Login Token</h2>
@using (Html.BeginForm("GetLoginToken", "Auth", null, FormMethod.Post))
{
<div class="editor-label">
  UserName
</div>

<div class="editor-field">
@Html.TextBox("username")
</div>

<div class="editor-label">
  Password
</div>

<div class="editor-field">
@Html.TextBox("password")
</div>
    
     <button type="submit">
                        Get Login Token</button>
    
    
}





Core/Cardinal.EasyApps.ED.WebServicies/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page - EasyDoc Servicios Web";
}

<h2>@ViewBag.Message</h2>

Core/Cardinal.EasyApps.ED.WebServicies/Views/Home/ValidarLoginToken.cshtml
@{
    ViewBag.Title = "ValidarLoginToken";
}

<h2>Validar Login Token</h2>
@using (Html.BeginForm("IsLoginTokenValid", "Auth", null, FormMethod.Post))
{
<div class="editor-label">
  Token
</div>

<div class="editor-field">
@Html.TextBox("loginToken")
</div>


    
     <button type="submit">
                        Validar Login Token</button>
    
    
}